export const Routes = {
  Splash: "Splash",
  Welcome: "Welcome",
  Onboarding: "Onboarding",
  AuthStack: "Auth",
  Login: "Login",
  Register: "Register",
  MainTabs: "MainTabs",
  Home: "Home",
  Tasks: "Tasks",
  Focus: "Focus",
  Odi: "Odi",
  Stats: "Stats",
  Profile: "Profile",
  Notifications: "Notifications",
  Settings: "Settings",
  Garden: "Garden",
  Friends: "Friends",
  AddFriend: "AddFriend",
  FriendsActivity: "FriendsActivity",
  FriendsLeaderboard: "FriendsLeaderboard",
  FriendsRequests: "FriendsRequests",
  FocusSettings: "FocusSettings",
  Achievements: "Achievements",
  Premium: "Premium",
  EditTask: "EditTask",
  Privacy: "Privacy",
} as const;
